// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkLlN_NSKGfsY1U1sQD0Yzc1d-3VW2pBQ',
    appId: '1:986887711210:web:a312908eb32cd9ac4b2a93',
    messagingSenderId: '986887711210',
    projectId: 'test-anything-4daa2',
    authDomain: 'test-anything-4daa2.firebaseapp.com',
    databaseURL: 'https://test-anything-4daa2-default-rtdb.firebaseio.com',
    storageBucket: 'test-anything-4daa2.appspot.com',
    measurementId: 'G-QHY2CR3H32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTM_f_bV6XCUYYDQM0d_i4v5AKU5LJsT0',
    appId: '1:986887711210:android:81083bcdab06ba174b2a93',
    messagingSenderId: '986887711210',
    projectId: 'test-anything-4daa2',
    databaseURL: 'https://test-anything-4daa2-default-rtdb.firebaseio.com',
    storageBucket: 'test-anything-4daa2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD37cB0QIx6Oi5OaPk2ZcAGsOZngpsJh3w',
    appId: '1:986887711210:ios:8ed23f86bda894aa4b2a93',
    messagingSenderId: '986887711210',
    projectId: 'test-anything-4daa2',
    databaseURL: 'https://test-anything-4daa2-default-rtdb.firebaseio.com',
    storageBucket: 'test-anything-4daa2.appspot.com',
    iosBundleId: 'com.example.astro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD37cB0QIx6Oi5OaPk2ZcAGsOZngpsJh3w',
    appId: '1:986887711210:ios:8ed23f86bda894aa4b2a93',
    messagingSenderId: '986887711210',
    projectId: 'test-anything-4daa2',
    databaseURL: 'https://test-anything-4daa2-default-rtdb.firebaseio.com',
    storageBucket: 'test-anything-4daa2.appspot.com',
    iosBundleId: 'com.example.astro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkLlN_NSKGfsY1U1sQD0Yzc1d-3VW2pBQ',
    appId: '1:986887711210:web:9e960c9f5d9839684b2a93',
    messagingSenderId: '986887711210',
    projectId: 'test-anything-4daa2',
    authDomain: 'test-anything-4daa2.firebaseapp.com',
    databaseURL: 'https://test-anything-4daa2-default-rtdb.firebaseio.com',
    storageBucket: 'test-anything-4daa2.appspot.com',
    measurementId: 'G-DKSCVVNRVM',
  );
}
